/**
 * The card catalog: the structural facts about a card that the rules need.
 *
 * TypeScript rather than JSON, and hand-maintained rather than scraped, for one reason: **Doctor
 * of Credit publishes offers, not card structure.** It will tell you the Platinum is at 175k after
 * $12k in 6 months. It will not tell you that the Platinum is a charge card and therefore exempt
 * from Amex's five-credit-card limit, that it outranks Gold and Green in a family and so forecloses
 * their bonuses forever, or that Spark Cash Plus is the one Capital One business card that stays
 * off your personal report. Those are the facts every rule in `rules/issuers.ts` actually turns on,
 * they are not on any page, and getting one wrong produces a confidently wrong answer.
 *
 * So the split is: structure here, curated and commented and reviewable in a diff; live offers in
 * `card-offers.json`, generated by `scripts/refresh-doc.ts` and disposable. A card with no current
 * offer stays here. An offer for a card that is not here is still shown, just without rule checks —
 * see `catalog()`.
 *
 * `card()` supplies issuer-wide defaults so each entry states only its exceptions. That is not
 * brevity for its own sake: an entry that lists sixteen fields hides which one is the interesting
 * one, and the interesting one is the whole reason the card is in the file.
 */

import type { Card, Currency, IssuerId, ProductType } from '../model.ts';

interface CardSeed {
  id: string;
  issuer: IssuerId;
  name: string;
  /** Dollars, converted to cents on the way in — nobody should be typing 69500 by hand. */
  fee?: number;
  feeWaivedFirstYear?: boolean;
  business?: boolean;
  currency?: Currency;
  /** Only worth stating for the business cards that break the rule. See `showsOnPersonalReport`. */
  showsOnPersonalReport?: boolean;
  charge?: boolean;
  family?: string;
  familyRank?: number;
  familyBonusCooldownMonths?: number;
  familyOnlyOneOpen?: boolean;
  bonusOncePerLifetime?: boolean;
  bonusCooldownMonths?: number | null;
  notes?: string;
}

function card(seed: CardSeed): Card {
  const productType: ProductType = seed.business ? 'business' : 'personal';
  return {
    id: seed.id,
    issuer: seed.issuer,
    name: seed.name,
    productType,
    annualFeeCents: Math.round((seed.fee ?? 0) * 100),
    annualFeeWaivedFirstYear: seed.feeWaivedFirstYear ?? false,
    currency: seed.currency ?? 'cash',
    // The default that matters: personal cards always report, business cards almost never do. The
    // exceptions are Capital One's (bar two) and Discover's, and each states it explicitly below.
    showsOnPersonalReport: seed.showsOnPersonalReport ?? productType === 'personal',
    chargeCard: seed.charge ?? false,
    family: seed.family ?? null,
    familyRank: seed.familyRank ?? 0,
    familyBonusCooldownMonths: seed.familyBonusCooldownMonths ?? null,
    familyOnlyOneOpen: seed.familyOnlyOneOpen ?? false,
    // Amex's offer terms say once per lifetime on every product; no other major issuer's do.
    bonusOncePerLifetime: seed.bonusOncePerLifetime ?? seed.issuer === 'amex',
    // Chase's blanket 24-month per-product rule. Stated as null for the handful with a longer or
    // stranger clock, which then use `familyBonusCooldownMonths` instead.
    bonusCooldownMonths:
      seed.bonusCooldownMonths === undefined
        ? seed.issuer === 'chase'
          ? 24
          : null
        : seed.bonusCooldownMonths,
    notes: seed.notes ?? '',
  };
}

/**
 * The cards the flowchart names, plus the ones DoC's best-bonus list keeps at the top.
 *
 * Ordered by issuer and then roughly by the flowchart's own priority within each, so the file
 * reads the way the chart does. Priority for recommendations is not taken from this order — it is
 * computed in `rules/recommend.ts` from the flowchart panels and the live offers.
 */
export const CARDS: Card[] = [
  // ---- Chase ---------------------------------------------------------------
  //
  // The Sapphire pair is the one place a 48-month clock is *shared*, and it is also "one at a
  // time". Both facts live on `family`, and both are why the flowchart puts Sapphire first: the
  // clock only starts once you take it.
  card({
    id: 'chase-sapphire-preferred',
    issuer: 'chase',
    name: 'Chase Sapphire Preferred',
    fee: 95,
    currency: 'ur',
    family: 'chase-sapphire',
    familyBonusCooldownMonths: 48,
    familyOnlyOneOpen: true,
    bonusCooldownMonths: null,
    notes: 'No bonus if you have received any Sapphire bonus in 48 months, or hold any Sapphire.',
  }),
  card({
    id: 'chase-sapphire-reserve',
    issuer: 'chase',
    name: 'Chase Sapphire Reserve',
    fee: 795,
    currency: 'ur',
    family: 'chase-sapphire',
    familyBonusCooldownMonths: 48,
    familyOnlyOneOpen: true,
    bonusCooldownMonths: null,
  }),
  card({ id: 'chase-united-quest', issuer: 'chase', name: 'Chase United Quest', fee: 350, currency: 'airline' }),
  card({
    id: 'chase-united-explorer',
    issuer: 'chase',
    name: 'Chase United Explorer',
    fee: 150,
    feeWaivedFirstYear: true,
    currency: 'airline',
  }),
  card({ id: 'chase-united-club', issuer: 'chase', name: 'Chase United Club Infinite', fee: 695, currency: 'airline' }),
  card({ id: 'chase-aeroplan', issuer: 'chase', name: 'Chase Aeroplan', fee: 95, currency: 'airline' }),
  // Southwest personal cards: you may hold only one at a time, and the Companion Pass is the
  // reason the flowchart cares about *when* the bonus posts rather than only whether it does.
  card({
    id: 'chase-southwest-priority',
    issuer: 'chase',
    name: 'Chase Southwest Rapid Rewards Priority',
    fee: 149,
    currency: 'airline',
    family: 'chase-southwest-personal',
    familyOnlyOneOpen: true,
    notes: 'Time the bonus to post in Jan/Feb to stretch the Companion Pass across almost two years.',
  }),
  card({
    id: 'chase-southwest-plus',
    issuer: 'chase',
    name: 'Chase Southwest Rapid Rewards Plus',
    fee: 69,
    currency: 'airline',
    family: 'chase-southwest-personal',
    familyOnlyOneOpen: true,
  }),
  card({
    id: 'chase-marriott-boundless',
    issuer: 'chase',
    name: 'Chase Marriott Bonvoy Boundless',
    fee: 95,
    currency: 'hotel',
    family: 'marriott',
    notes: 'Read the Marriott panel first — eligibility is entangled with the Amex Marriott cards.',
  }),
  card({
    id: 'chase-marriott-bountiful',
    issuer: 'chase',
    name: 'Chase Marriott Bonvoy Bountiful',
    fee: 250,
    currency: 'hotel',
    family: 'marriott',
  }),
  card({ id: 'chase-ihg-premier', issuer: 'chase', name: 'Chase IHG One Rewards Premier', fee: 99, currency: 'hotel' }),
  card({ id: 'chase-hyatt', issuer: 'chase', name: 'Chase World of Hyatt', fee: 95, currency: 'hotel' }),
  card({ id: 'chase-british-airways', issuer: 'chase', name: 'Chase British Airways', fee: 95, currency: 'airline' }),
  card({ id: 'chase-aer-lingus', issuer: 'chase', name: 'Chase Aer Lingus', fee: 95, currency: 'airline' }),
  card({ id: 'chase-iberia', issuer: 'chase', name: 'Chase Iberia', fee: 95, currency: 'airline' }),
  card({ id: 'chase-freedom-flex', issuer: 'chase', name: 'Chase Freedom Flex', currency: 'ur' }),
  card({ id: 'chase-freedom-unlimited', issuer: 'chase', name: 'Chase Freedom Unlimited', currency: 'ur' }),
  card({ id: 'chase-ink-cash', issuer: 'chase', name: 'Chase Ink Business Cash', business: true, currency: 'ur' }),
  card({ id: 'chase-ink-unlimited', issuer: 'chase', name: 'Chase Ink Business Unlimited', business: true, currency: 'ur' }),
  card({ id: 'chase-ink-preferred', issuer: 'chase', name: 'Chase Ink Business Preferred', fee: 95, business: true, currency: 'ur' }),
  card({ id: 'chase-ink-premier', issuer: 'chase', name: 'Chase Ink Business Premier', fee: 195, business: true, currency: 'cash' }),
  // A separate card from the personal Sapphire Reserve, and deliberately *not* in the Sapphire
  // family: it is a business card, so it neither burns a 5/24 slot nor shares the personal cards'
  // 48-month clock. Worth a catalog entry mostly so that Doctor of Credit's heading for it stops
  // being matched to the personal card, which would have applied both of those rules wrongly.
  card({ id: 'chase-sapphire-reserve-business', issuer: 'chase', name: 'Chase Sapphire Reserve for Business', fee: 795, business: true, currency: 'ur' }),
  card({ id: 'chase-united-business', issuer: 'chase', name: 'Chase United Business', fee: 99, business: true, currency: 'airline' }),
  card({ id: 'chase-hyatt-business', issuer: 'chase', name: 'Chase World of Hyatt Business', fee: 199, business: true, currency: 'hotel' }),
  card({ id: 'chase-southwest-premier-business', issuer: 'chase', name: 'Chase Southwest Premier Business', fee: 99, business: true, currency: 'airline' }),
  card({ id: 'chase-southwest-performance-business', issuer: 'chase', name: 'Chase Southwest Performance Business', fee: 199, business: true, currency: 'airline' }),
  card({ id: 'chase-ihg-business', issuer: 'chase', name: 'Chase IHG One Rewards Business', fee: 99, business: true, currency: 'hotel' }),

  // ---- Amex ----------------------------------------------------------------
  //
  // The family ranks below are the mechanism behind the flowchart's strongest recent piece of
  // advice — "we now recommend avoiding Amex personal cards until 5+/24". Taking Platinum first
  // does not delay Gold and Green, it destroys them, so the ordering is not a preference.
  card({
    id: 'amex-platinum',
    issuer: 'amex',
    name: 'Amex Platinum',
    fee: 895,
    currency: 'mr',
    charge: true,
    family: 'amex-mr-personal',
    familyRank: 3,
    notes: 'Charge card: exempt from the five-credit-card limit and from 2/90.',
  }),
  card({
    id: 'amex-gold',
    issuer: 'amex',
    name: 'Amex Gold',
    fee: 325,
    currency: 'mr',
    charge: true,
    family: 'amex-mr-personal',
    familyRank: 2,
  }),
  card({
    id: 'amex-green',
    issuer: 'amex',
    name: 'Amex Green',
    fee: 150,
    currency: 'mr',
    charge: true,
    family: 'amex-mr-personal',
    familyRank: 1,
  }),
  card({ id: 'amex-business-platinum', issuer: 'amex', name: 'Amex Business Platinum', fee: 895, business: true, currency: 'mr', charge: true }),
  card({ id: 'amex-business-gold', issuer: 'amex', name: 'Amex Business Gold', fee: 375, business: true, currency: 'mr', charge: true }),
  card({
    id: 'amex-blue-business-plus',
    issuer: 'amex',
    name: 'Amex Blue Business Plus',
    business: true,
    currency: 'mr',
    notes: 'The flowchart\'s pick of keeper: 2x on everything, no fee, keeps an MR account alive for free.',
  }),
  card({ id: 'amex-blue-business-cash', issuer: 'amex', name: 'Amex Blue Business Cash', business: true, currency: 'cash' }),
  // The Blue Cash family gets the same rank treatment as the MR cards: Preferred outranks
  // Everyday, so taking Preferred first costs you Everyday's bonus permanently.
  card({
    id: 'amex-blue-cash-preferred',
    issuer: 'amex',
    name: 'Amex Blue Cash Preferred',
    fee: 95,
    currency: 'cash',
    family: 'amex-blue-cash',
    familyRank: 2,
  }),
  card({
    id: 'amex-blue-cash-everyday',
    issuer: 'amex',
    name: 'Amex Blue Cash Everyday',
    currency: 'cash',
    family: 'amex-blue-cash',
    familyRank: 1,
  }),
  card({
    id: 'amex-delta-reserve',
    issuer: 'amex',
    name: 'Amex Delta SkyMiles Reserve',
    fee: 650,
    currency: 'airline',
    family: 'amex-delta-personal',
    familyRank: 4,
  }),
  card({
    id: 'amex-delta-platinum',
    issuer: 'amex',
    name: 'Amex Delta SkyMiles Platinum',
    fee: 350,
    currency: 'airline',
    family: 'amex-delta-personal',
    familyRank: 3,
  }),
  card({
    id: 'amex-delta-gold',
    issuer: 'amex',
    name: 'Amex Delta SkyMiles Gold',
    fee: 150,
    feeWaivedFirstYear: true,
    currency: 'airline',
    family: 'amex-delta-personal',
    familyRank: 2,
  }),
  card({
    id: 'amex-delta-blue',
    issuer: 'amex',
    name: 'Amex Delta SkyMiles Blue',
    currency: 'airline',
    family: 'amex-delta-personal',
    familyRank: 1,
    notes: 'Skip regardless — the bonus is too small to be worth a family slot.',
  }),
  card({ id: 'amex-delta-business-gold', issuer: 'amex', name: 'Amex Delta SkyMiles Business Gold', fee: 150, business: true, currency: 'airline' }),
  card({ id: 'amex-delta-business-platinum', issuer: 'amex', name: 'Amex Delta SkyMiles Business Platinum', fee: 350, business: true, currency: 'airline' }),
  // Personal Hilton is the one Amex family the rank rules have *not* reached, per the flowchart.
  // Left unranked deliberately rather than guessed at.
  card({ id: 'amex-hilton-honors', issuer: 'amex', name: 'Amex Hilton Honors', currency: 'hotel' }),
  card({ id: 'amex-hilton-surpass', issuer: 'amex', name: 'Amex Hilton Honors Surpass', fee: 150, currency: 'hotel' }),
  card({ id: 'amex-hilton-aspire', issuer: 'amex', name: 'Amex Hilton Honors Aspire', fee: 550, currency: 'hotel' }),
  card({ id: 'amex-hilton-business', issuer: 'amex', name: 'Amex Hilton Honors Business', fee: 195, business: true, currency: 'hotel' }),
  card({
    id: 'amex-marriott-brilliant',
    issuer: 'amex',
    name: 'Amex Marriott Bonvoy Brilliant',
    fee: 650,
    currency: 'hotel',
    family: 'marriott',
    familyRank: 3,
  }),
  card({
    id: 'amex-marriott-bevy',
    issuer: 'amex',
    name: 'Amex Marriott Bonvoy Bevy',
    fee: 250,
    currency: 'hotel',
    family: 'marriott',
    familyRank: 2,
    notes: 'Needs Boundless and Bountiful closed for 30 days first, and is barred outright if you have had Brilliant.',
  }),
  card({ id: 'amex-marriott-business', issuer: 'amex', name: 'Amex Marriott Bonvoy Business', fee: 125, business: true, currency: 'hotel' }),

  // ---- Citi ----------------------------------------------------------------
  //
  // The ThankYou family shares a 48-month clock the same way Sapphire does, which is the whole
  // point of the flowchart's "Good to start the 4-year timer sooner rather than later".
  card({
    id: 'citi-strata-premier',
    issuer: 'citi',
    name: 'Citi Strata Premier',
    fee: 95,
    currency: 'typ',
    family: 'citi-thankyou',
    familyBonusCooldownMonths: 48,
    notes: 'Very inquiry-sensitive; often wants 0–1/6.',
  }),
  card({
    id: 'citi-strata-elite',
    issuer: 'citi',
    name: 'Citi Strata Elite',
    fee: 595,
    currency: 'typ',
    family: 'citi-thankyou',
    familyBonusCooldownMonths: 48,
  }),
  card({
    id: 'citi-custom-cash',
    issuer: 'citi',
    name: 'Citi Custom Cash',
    currency: 'typ',
    notes: 'Not in the 48-month ThankYou family — the flowchart calls it a way to add TYP without resetting that clock.',
  }),
  card({ id: 'citi-double-cash', issuer: 'citi', name: 'Citi Double Cash', currency: 'typ' }),
  card({ id: 'citi-aa-platinum', issuer: 'citi', name: 'Citi AAdvantage Platinum Select', fee: 99, feeWaivedFirstYear: true, currency: 'airline', bonusCooldownMonths: 48 }),
  card({ id: 'citi-aa-executive', issuer: 'citi', name: 'Citi AAdvantage Executive', fee: 695, currency: 'airline', bonusCooldownMonths: 48 }),
  card({ id: 'citi-aa-business', issuer: 'citi', name: 'Citi AAdvantage Business', fee: 99, feeWaivedFirstYear: true, business: true, currency: 'airline', bonusCooldownMonths: 48, notes: 'Usually wants five years of credit history.' }),

  // ---- Capital One ---------------------------------------------------------
  //
  // The exception that has to be right: Cap1 business cards report to your personal bureau and so
  // burn a 5/24 slot, *except* these two. Marking them wrong either way misleads.
  card({ id: 'capitalone-venture', issuer: 'capitalone', name: 'Capital One Venture', fee: 95, currency: 'venture' }),
  card({ id: 'capitalone-venture-x', issuer: 'capitalone', name: 'Capital One Venture X', fee: 395, currency: 'venture' }),
  card({ id: 'capitalone-savor', issuer: 'capitalone', name: 'Capital One Savor', currency: 'venture' }),
  card({
    id: 'capitalone-spark-cash-plus',
    issuer: 'capitalone',
    name: 'Capital One Spark Cash Plus',
    fee: 150,
    business: true,
    currency: 'cash',
    showsOnPersonalReport: false,
    notes: 'One of only two Cap1 business cards that stay off your personal report.',
  }),
  card({
    id: 'capitalone-venture-x-business',
    issuer: 'capitalone',
    name: 'Capital One Venture X Business',
    fee: 395,
    business: true,
    currency: 'venture',
    showsOnPersonalReport: false,
  }),
  card({
    id: 'capitalone-spark-miles',
    issuer: 'capitalone',
    name: 'Capital One Spark Miles',
    fee: 95,
    feeWaivedFirstYear: true,
    business: true,
    currency: 'venture',
    showsOnPersonalReport: true,
    notes: 'Reports to your personal bureau, unlike most business cards — it will burn a 5/24 slot.',
  }),

  // ---- Bank of America -----------------------------------------------------
  card({ id: 'boa-alaska', issuer: 'boa', name: 'BoA Alaska Airlines', fee: 95, currency: 'airline' }),
  card({ id: 'boa-alaska-business', issuer: 'boa', name: 'BoA Alaska Airlines Business', fee: 70, business: true, currency: 'airline' }),
  card({ id: 'boa-virgin-atlantic', issuer: 'boa', name: 'BoA Virgin Atlantic', fee: 103, currency: 'airline' }),
  card({ id: 'boa-air-france', issuer: 'boa', name: 'BoA Air France KLM', fee: 89, currency: 'airline' }),
  card({ id: 'boa-premium-rewards', issuer: 'boa', name: 'BoA Premium Rewards', fee: 95, currency: 'cash' }),
  card({ id: 'boa-premium-rewards-elite', issuer: 'boa', name: 'BoA Premium Rewards Elite', fee: 550, currency: 'cash' }),
  card({ id: 'boa-business-unlimited', issuer: 'boa', name: 'BoA Business Advantage Unlimited Cash', business: true, currency: 'cash' }),
  card({ id: 'boa-business-customized', issuer: 'boa', name: 'BoA Business Advantage Customized Cash', business: true, currency: 'cash' }),

  // ---- Barclays ------------------------------------------------------------
  card({ id: 'barclays-jetblue-plus', issuer: 'barclays', name: 'Barclays JetBlue Plus', fee: 99, currency: 'airline' }),
  card({ id: 'barclays-jetblue-business', issuer: 'barclays', name: 'Barclays JetBlue Business', fee: 99, business: true, currency: 'airline' }),
  card({ id: 'barclays-hawaiian', issuer: 'barclays', name: 'Barclays Hawaiian Airlines', fee: 99, currency: 'airline' }),
  card({ id: 'barclays-wyndham-earner-premier', issuer: 'barclays', name: 'Barclays Wyndham Rewards Earner Premier', fee: 395, currency: 'hotel' }),
  card({ id: 'barclays-wyndham-business', issuer: 'barclays', name: 'Barclays Wyndham Rewards Earner Business', fee: 95, business: true, currency: 'hotel' }),
  card({ id: 'barclays-aviator-red', issuer: 'barclays', name: 'Barclays AAdvantage Aviator Red', fee: 99, currency: 'airline' }),

  // ---- US Bank -------------------------------------------------------------
  card({ id: 'usbank-altitude-reserve', issuer: 'usbank', name: 'U.S. Bank Altitude Reserve', fee: 400, currency: 'cash', notes: 'Usually described as wanting 0/6 inquiries.' }),
  card({ id: 'usbank-altitude-connect', issuer: 'usbank', name: 'U.S. Bank Altitude Connect', fee: 95, currency: 'cash' }),
  card({ id: 'usbank-flexperks-gold', issuer: 'usbank', name: 'U.S. Bank FlexPerks Gold', fee: 85, currency: 'cash' }),
  card({ id: 'usbank-leverage', issuer: 'usbank', name: 'U.S. Bank Leverage Business', business: true, currency: 'cash' }),
  card({ id: 'usbank-business-altitude-connect', issuer: 'usbank', name: 'U.S. Bank Business Altitude Connect', fee: 95, feeWaivedFirstYear: true, business: true, currency: 'cash' }),
  card({ id: 'usbank-triple-cash-business', issuer: 'usbank', name: 'U.S. Bank Triple Cash Rewards Business', business: true, currency: 'cash', notes: 'Be very careful with manufactured spend on U.S. Bank business cards.' }),

  // ---- Wells Fargo ---------------------------------------------------------
  card({ id: 'wellsfargo-autograph-journey', issuer: 'wellsfargo', name: 'Wells Fargo Autograph Journey', fee: 95, currency: 'wf' }),
  card({ id: 'wellsfargo-autograph', issuer: 'wellsfargo', name: 'Wells Fargo Autograph', currency: 'wf' }),
  card({
    id: 'wellsfargo-signify-business',
    issuer: 'wellsfargo',
    name: 'Wells Fargo Signify Business Cash',
    business: true,
    currency: 'cash',
    notes: 'Requires an existing Wells Fargo bank account; reports vary between 2 months and a year of age.',
  }),

  // ---- everything else the flowchart names --------------------------------
  card({
    id: 'bilt',
    issuer: 'bilt',
    name: 'Bilt Mastercard',
    currency: 'bilt',
    notes: 'Only worth a 5/24 slot at roughly $4k+/month rent, with other spend to spare.',
  }),
  card({
    id: 'discover-it',
    issuer: 'discover',
    name: 'Discover it',
    currency: 'cash',
    notes: 'The flowchart\'s starter pick: the only decent rewards card reliably approved with no credit history.',
  }),
  card({
    id: 'discover-it-business',
    issuer: 'discover',
    name: 'Discover it Business',
    business: true,
    currency: 'cash',
    showsOnPersonalReport: true,
    notes: 'Discover business cards report to your personal bureau — avoid while under 5/24.',
  }),
  card({ id: 'penfed-pathfinder', issuer: 'penfed', name: 'PenFed Pathfinder', fee: 95, currency: 'cash' }),
  card({ id: 'navyfed-flagship', issuer: 'navyfed', name: 'Navy Federal Flagship Rewards', fee: 49, currency: 'cash' }),
  card({ id: 'truist-premium-business', issuer: 'truist', name: 'Truist Premium Business', fee: 0, business: true, currency: 'cash' }),

  // ---- cards the flowchart does not rank, but DoC keeps listing ------------
  //
  // Added so the offer scraper can attach a live bonus to *something* with a known issuer and
  // product type. They get full rule coverage — a personal card here still burns a 5/24 slot, and
  // Amex's lifetime rule still applies — they simply have no place in the flowchart's ordered
  // columns, so `scoreOver524` files them below every card that does.
  card({ id: 'amex-everyday', issuer: 'amex', name: 'Amex EveryDay', currency: 'mr' }),
  card({ id: 'amex-everyday-preferred', issuer: 'amex', name: 'Amex EveryDay Preferred', fee: 95, currency: 'mr' }),
  card({ id: 'usbank-cash-plus', issuer: 'usbank', name: 'U.S. Bank Cash+', currency: 'cash' }),
  card({ id: 'usbank-shopper-cash', issuer: 'usbank', name: 'U.S. Bank Shopper Cash', currency: 'cash' }),
  card({ id: 'usbank-amazon-prime-business', issuer: 'usbank', name: 'U.S. Bank Amazon Prime Business', business: true, currency: 'cash' }),
  card({ id: 'wellsfargo-active-cash', issuer: 'wellsfargo', name: 'Wells Fargo Active Cash', currency: 'cash' }),
  card({ id: 'wellsfargo-choice-privileges', issuer: 'wellsfargo', name: 'Wells Fargo Choice Privileges', currency: 'hotel' }),
  card({ id: 'boa-unlimited-cash-rewards', issuer: 'boa', name: 'BoA Unlimited Cash Rewards', currency: 'cash' }),
  card({ id: 'boa-customized-cash-rewards', issuer: 'boa', name: 'BoA Customized Cash Rewards', currency: 'cash' }),
  card({ id: 'boa-business-travel-rewards', issuer: 'boa', name: 'BoA Business Advantage Travel Rewards', business: true, currency: 'cash' }),
  // Both report to your personal bureau, like every Cap1 business card bar Spark Cash Plus and
  // Venture X Business. That is the whole reason they are worth listing separately.
  card({ id: 'capitalone-spark-cash-select', issuer: 'capitalone', name: 'Capital One Spark Cash Select', business: true, currency: 'cash', showsOnPersonalReport: true }),
  card({ id: 'capitalone-venture-one-business', issuer: 'capitalone', name: 'Capital One VentureOne Business', business: true, currency: 'venture', showsOnPersonalReport: true }),
  card({ id: 'barclays-gm-business', issuer: 'barclays', name: 'Barclays GM Business', business: true, currency: 'cash' }),
  card({ id: 'synchrony-virgin-red', issuer: 'synchrony', name: 'Synchrony Virgin Red', currency: 'airline' }),
  card({ id: 'discover-it-miles', issuer: 'discover', name: 'Discover it Miles', currency: 'cash' }),
  card({ id: 'citi-att-points-plus', issuer: 'citi', name: 'Citi AT&T Points Plus', currency: 'typ' }),
];

/** By id, for following `CardAccount.cardId`. */
export const CARDS_BY_ID: Record<string, Card> = Object.fromEntries(
  CARDS.map((entry) => [entry.id, entry]),
);

/**
 * What to call a family out loud.
 *
 * The slugs above are identifiers and read like it — a rule message that says "the chase-sapphire
 * family shares one clock" is the app showing its internals to someone who just wants to know
 * whether they can apply. `familyName` is what goes in front of a user.
 */
const FAMILY_NAMES: Record<string, string> = {
  'chase-sapphire': 'Sapphire',
  'chase-southwest-personal': 'Southwest personal',
  'amex-mr-personal': 'Amex personal Membership Rewards',
  'amex-blue-cash': 'Amex Blue Cash',
  'amex-delta-personal': 'Amex personal Delta',
  'citi-thankyou': 'Citi ThankYou',
  marriott: 'Marriott',
};

export function familyName(family: string | null): string {
  if (family === null) return '';
  return FAMILY_NAMES[family] ?? family;
}

/**
 * A card for an id that may not be in the catalog.
 *
 * Returns a plausible stand-in rather than null, so that a user-entered card or an offer for
 * something never curated still gets *some* rule coverage: personal-report and the cross-issuer
 * cooldowns are inferable from the issuer alone, and applying only those beats applying none.
 * The stand-in is deliberately permissive — it claims no family and no lifetime language — because
 * inventing a restriction is worse than missing one. `known` says which it is.
 */
export function catalog(cardId: string): { card: Card; known: boolean } {
  const found = CARDS_BY_ID[cardId];
  if (found) return { card: found, known: true };
  return {
    card: card({ id: cardId, issuer: 'other', name: cardId, bonusOncePerLifetime: false }),
    known: false,
  };
}

export function cardsByIssuer(issuer: IssuerId): Card[] {
  return CARDS.filter((entry) => entry.issuer === issuer);
}
